/** Transitional re-exports — prefer module-local api/endpoints */
export { AUTH_ENDPOINTS } from '@/modules/auth/endpoints'
export { PROFILE_ENDPOINTS } from '@/modules/auth/endpoints'
export { WORKSPACE_ONBOARDING_ENDPOINTS } from '@/modules/auth/endpoints'
export { ORG_ENDPOINTS } from '@/modules/org/endpoints'
export { ORG_INVITE_ENDPOINTS } from '@/modules/org/endpoints'
export { PROJECT_ENDPOINTS } from '@/modules/projects/endpoints'
export { AI_ENDPOINTS } from '@/modules/projects/endpoints'
export { SESSION_ENDPOINTS } from '@/modules/sessions/endpoints'
export { DOCUMENT_ENDPOINTS } from '@/modules/documents/endpoints'
export { PROJECT_SECTION_ENDPOINTS } from '@/modules/documents/endpoints'
export { DOCUMENT_TEMPLATE_ENDPOINTS } from '@/modules/documents/endpoints'
export { LANDSCAPE_ENDPOINTS } from '@/modules/landscape/endpoints'
export { COLLABORATION_ENDPOINTS } from '@/modules/collaboration/endpoints'
export { AI_DOCUMENT_ENDPOINTS } from '@/modules/ai-document-intelligence/document-ai/infrastructure/api/endpoints'
export { DOCUMENT_HUB_ENDPOINTS } from '@/modules/documents/endpoints'
export { CONTROLLED_LIST_ENDPOINTS } from '@/modules/controlled-lists/endpoints'
export { CONTROLLED_VALUE_ENDPOINTS } from '@/modules/controlled-lists/endpoints'
