/** Transitional re-exports — prefer module-local api/endpoints */
export { AUTH_ENDPOINTS } from '@/modules/auth/auth/api/endpoints'
export { PROFILE_ENDPOINTS } from '@/modules/auth/profile/api/endpoints'
export { ORG_ENDPOINTS } from '@/modules/org/org/api/endpoints'
export { ORG_INVITE_ENDPOINTS } from '@/modules/org/invites/api/endpoints'
export { TEMPLATE_ENDPOINTS, ADMIN_ENDPOINTS } from '@/modules/admin/admin-templates/api/endpoints'
export { PROJECT_ENDPOINTS } from '@/modules/projects/project/api/endpoints'
export { AI_ENDPOINTS } from '@/modules/projects/project/api/ai-endpoints'
export { SESSION_ENDPOINTS } from '@/modules/sessions/session/api/endpoints'
export { DOCUMENT_ENDPOINTS } from '@/modules/documents/document/api/endpoints'
export { PROJECT_SECTION_ENDPOINTS } from '@/modules/documents/project-sections/api/endpoints'
export { DOCUMENT_TEMPLATE_ENDPOINTS } from '@/modules/documents/document-templates/api/endpoints'
export { LANDSCAPE_ENDPOINTS } from '@/modules/landscape/landscape/api/endpoints'
export { COLLABORATION_ENDPOINTS } from '@/modules/collaboration/core/api/endpoints'
export { AI_DOCUMENT_ENDPOINTS } from '@/modules/ai-document-intelligence/document-ai/api/endpoints'
export { DOCUMENT_HUB_ENDPOINTS } from '@/modules/documents/document-hub/api/endpoints'
export { CONTROLLED_LIST_ENDPOINTS } from '@/modules/controlled-lists/lists/api/endpoints'
export { CONTROLLED_VALUE_ENDPOINTS } from '@/modules/controlled-lists/values/api/endpoints'
