export type AIAgentStatus = 'active' | 'inactive' | 'deprecated'
export type AIAgentVersionStatus = 'draft' | 'testing' | 'published' | 'archived'
export type AIRunMode =
  | 'generate'
  | 'improve'
  | 'assess'
  | 'extract'
  | 'classify'
  | 'compare'
  | 'summarize'
  | 'recommend'
  | 'validate'
export type AIModelTier = 'economy' | 'standard' | 'premium' | 'frontier'
export type AIRunStatus = 'success' | 'failed' | 'cancelled' | 'skipped'
