/** Admin route path helpers. */
export const ADMIN_ROUTES = {
  templates: '/admin/templates',
  templateNew: '/admin/templates/new',
  template: (templateId: string) => `/admin/templates/${templateId}`,
  documents: '/admin/documents',
  aiAgents: '/admin/ai-agents',
  aiBudgets: '/admin/ai-budgets',
  aiAgent: (agentId: string) => `/admin/ai-agents/${agentId}`,
  aiAgentVersion: (agentId: string, versionId: string) =>
    `/admin/ai-agents/${agentId}/versions/${versionId}`,
  developerTools: '/admin/ai',

  /** Wave 5 — AI & Automation Control Center */
  aiControl: '/admin/ai-control',
  aiControlOverview: '/admin/ai-control/overview',
  aiControlProviders: '/admin/ai-control/providers',
  aiControlProvider: (providerId: string) => `/admin/ai-control/providers/${providerId}`,
  aiControlProviderSecrets: '/admin/ai-control/provider-secrets',
  aiControlProviderSecret: (secretId: string) =>
    `/admin/ai-control/provider-secrets/${secretId}`,
  aiControlModels: '/admin/ai-control/models',
  aiControlModel: (modelId: string) => `/admin/ai-control/models/${modelId}`,
  aiControlDeployments: '/admin/ai-control/deployments',
  aiControlDeployment: (deploymentId: string) =>
    `/admin/ai-control/deployments/${deploymentId}`,
  aiControlParameterCapabilities: '/admin/ai-control/parameter-capabilities',
  aiControlAgents: '/admin/ai-control/agents',
  aiControlAgent: (agentId: string) => `/admin/ai-control/agents/${agentId}`,
  aiControlPrompts: '/admin/ai-control/prompts',
  aiControlPrompt: (templateId: string) => `/admin/ai-control/prompts/${templateId}`,
  aiControlPromptVersion: (templateId: string, versionId: string) =>
    `/admin/ai-control/prompts/${templateId}/versions/${versionId}`,
  aiControlEventConfigs: '/admin/ai-control/event-configs',
  aiControlEventConfig: (eventConfigId: string) =>
    `/admin/ai-control/event-configs/${eventConfigId}`,
  aiControlUsagePolicies: '/admin/ai-control/usage-policies',
  aiControlUsagePolicy: (policyId: string) =>
    `/admin/ai-control/usage-policies/${policyId}`,
  aiControlExecutions: '/admin/ai-control/executions',
  aiControlExecution: (executionLogId: string) =>
    `/admin/ai-control/executions/${executionLogId}`,
  aiControlPlayground: '/admin/ai-control/playground',
  aiControlTools: '/admin/ai-control/tools',
  aiControlTool: (toolId: string) => `/admin/ai-control/tools/${toolId}`,
  aiControlAssistantSettings: '/admin/ai-control/assistant-settings',
  aiControlKnowledge: '/admin/ai-control/knowledge',

  iam: '/admin/iam',
  iamOverview: '/admin/iam/overview',
  iamUsers: '/admin/iam/users',
  iamUserNew: '/admin/iam/users/new',
  iamUser: (userId: string) => `/admin/iam/users/${userId}`,
  iamRoles: '/admin/iam/roles',
  iamRoleNew: '/admin/iam/roles/new',
  iamRole: (roleId: string) => `/admin/iam/roles/${roleId}`,
  iamRoleAssignments: '/admin/iam/role-assignments',
  iamPermissions: '/admin/iam/permissions',
  iamResources: '/admin/iam/resources',
  iamResource: (resourceId: string) => `/admin/iam/resources/${resourceId}`,
  iamGrants: '/admin/iam/grants',
  iamGrantNew: '/admin/iam/grants/new',
  iamGrant: (grantId: string) => `/admin/iam/grants/${grantId}`,
  iamDelegations: '/admin/iam/delegations',
  iamDelegationNew: '/admin/iam/delegations/new',
  iamOwnerPolicies: '/admin/iam/owner-policies',
  iamOwnerPolicyNew: '/admin/iam/owner-policies/new',
  iamAuthorizationCheck: '/admin/iam/authorization/check',
  iamAuthorizationExplain: '/admin/iam/authorization/explain',
  /** @deprecated Prefer platformAuditEvents — kept for redirects */
  iamAudit: '/admin/iam/audit',
  /** @deprecated Prefer iamGrantNew — kept for redirects */
  iamAccessControl: '/admin/iam/access-control',
  /** @deprecated Prefer platformAuditEvents — kept for redirects */
  iamAuditLog: '/admin/iam/audit-log',
  /** @deprecated Prefer iamPermissions — kept for redirects */
  iamRights: '/admin/iam/rights',
  organizations: '/admin/organizations',
  organizationNew: '/admin/organizations/new',
  organization: (orgId: string) => `/admin/organizations/${orgId}`,
  organizationMembers: (orgId: string) => `/admin/organizations/${orgId}/members`,
  organizationInvitations: (orgId: string) => `/admin/organizations/${orgId}/invitations`,
  organizationTeams: (orgId: string) => `/admin/organizations/${orgId}/teams`,
  organizationWorkspaces: (orgId: string) => `/admin/organizations/${orgId}/workspaces`,
  organizationActivity: (orgId: string) => `/admin/organizations/${orgId}/activity`,
  workspaces: '/admin/workspaces',
  workspaceNew: '/admin/workspaces/new',
  workspace: (workspaceId: string) => `/admin/workspaces/${workspaceId}`,
  workspaceMembers: (workspaceId: string) => `/admin/workspaces/${workspaceId}/members`,
  workspaceTeams: (workspaceId: string) => `/admin/workspaces/${workspaceId}/teams`,
  workspaceAccess: (workspaceId: string) => `/admin/workspaces/${workspaceId}/access`,
  workspaceClients: (workspaceId: string) => `/admin/workspaces/${workspaceId}/clients`,
  workspaceRateCards: (workspaceId: string) => `/admin/workspaces/${workspaceId}/rates/cards`,
  workspaceRateCard: (workspaceId: string, rateCardId: string) =>
    `/admin/workspaces/${workspaceId}/rates/cards/${rateCardId}`,
  workspaceRateSetup: (workspaceId: string) => `/admin/workspaces/${workspaceId}/rates/setup`,
  workspaceRateResolve: (workspaceId: string) => `/admin/workspaces/${workspaceId}/rates/resolve`,
  workspaceConfig: (workspaceId: string) => `/admin/workspaces/${workspaceId}/config`,
  workspaceConfigFields: (workspaceId: string) => `/admin/workspaces/${workspaceId}/config/fields`,
  workspaceConfigForms: (workspaceId: string) => `/admin/workspaces/${workspaceId}/config/forms`,
  workspaceConfigForm: (workspaceId: string, formId: string) =>
    `/admin/workspaces/${workspaceId}/config/forms/${formId}`,
  workspaceConfigUiMetadata: (workspaceId: string) =>
    `/admin/workspaces/${workspaceId}/config/ui-metadata`,
  /** Phase 04 — Platform Reliability */
  platform: '/admin/platform',
  platformOverview: '/admin/platform/overview',
  platformActivityLogs: '/admin/platform/activity-logs',
  platformActivityLog: (activityId: string) => `/admin/platform/activity-logs/${activityId}`,
  platformAuditEvents: '/admin/platform/audit-events',
  platformAuditEvent: (auditEventId: string) => `/admin/platform/audit-events/${auditEventId}`,
  platformEventOutbox: '/admin/platform/event-outbox',
  platformEventOutboxDetail: (outboxId: string) => `/admin/platform/event-outbox/${outboxId}`,
  platformDeadLetters: '/admin/platform/dead-letters',
  platformEmailOutbox: '/admin/platform/email-outbox',
  platformEmailOutboxDetail: (emailOutboxId: string) =>
    `/admin/platform/email-outbox/${emailOutboxId}`,
  platformIdempotency: '/admin/platform/idempotency',
  platformIdempotencyDetail: (recordId: string) => `/admin/platform/idempotency/${recordId}`,
  platformJobs: '/admin/platform/jobs',
  platformJobExecution: (jobCode: string, executionId: string) =>
    `/admin/platform/jobs/${jobCode}/executions/${executionId}`,
  platformTraces: '/admin/platform/traces',
  platformErrors: '/admin/platform/errors',
  platformEventDefinitions: '/admin/platform/event-definitions',
  platformSettings: '/admin/platform/settings',
  /** Wave 2 P6 — Project standards */
  phaseDefinitions: '/admin/project-standards/phase-definitions',
  projectTemplates: '/admin/project-standards/templates',
  projectTemplateBuilder: (templateId: string) =>
    `/admin/project-standards/templates/${templateId}/builder`,
  /** Wave 2 P6 — NAD */
  nadOverview: '/admin/notifications/overview',
  nadEmailRules: '/admin/notifications/email-rules',
  nadEmailTemplates: '/admin/notifications/email-templates',
  nadDeliveries: '/admin/notifications/deliveries',
  nadAutomation: '/admin/notifications/automation',
} as const
