'use client'

import { Button, Input, Select, Typography } from '@/shared/ui'
import type { GovernanceSimulatorViewProps } from '@/types/governance/governance-simulator'

export function GovernanceSimulatorView({
  canViewRuleDetails,
  form,
  loading,
  error,
  result,
  scenarioOptions,
  actionKeyOptions,
  onScenarioSelect,
  onFormFieldChange,
  onEvaluate,
  onReset,
}: GovernanceSimulatorViewProps) {
  return (
    <div className="space-y-4 rounded-md border border-dashed border-border p-4">
      <Typography variant="small" className="font-medium">
        Policy simulator (dry-run)
      </Typography>
      <Typography variant="small" tone="muted">
        Tests governance evaluation without mutating data. Does not load hidden documents or answers.
      </Typography>

      <Select
        label="Sample scenario"
        value=""
        onValueChange={(v: string) => {
          if (v) onScenarioSelect(v)
        }}
        options={scenarioOptions}
      />

      <Select
        label="Action key"
        value={form.action_key}
        onValueChange={(v: string) => onFormFieldChange('action_key', v)}
        options={actionKeyOptions}
      />

      <div className="grid gap-3 md:grid-cols-2">
        <Input
          label="Project ID (optional)"
          value={form.project_id}
          onChange={(e) => onFormFieldChange('project_id', e.target.value)}
        />
        <Input
          label="Actor role"
          value={form.actor_role}
          onChange={(e) => onFormFieldChange('actor_role', e.target.value)}
        />
        <Input
          label="Project role"
          value={form.project_role}
          onChange={(e) => onFormFieldChange('project_role', e.target.value)}
        />
        <Input
          label="Workflow status"
          value={form.workflow_status}
          onChange={(e) => onFormFieldChange('workflow_status', e.target.value)}
        />
        <Input
          label="Readiness status"
          value={form.readiness_status}
          onChange={(e) => onFormFieldChange('readiness_status', e.target.value)}
        />
        <Input
          label="Lifecycle status"
          value={form.lifecycle_status}
          onChange={(e) => onFormFieldChange('lifecycle_status', e.target.value)}
        />
        <Input
          label="Target workflow status"
          value={form.target_workflow_status}
          onChange={(e) => onFormFieldChange('target_workflow_status', e.target.value)}
        />
        <Input
          label="Document type"
          value={form.document_type}
          onChange={(e) => onFormFieldChange('document_type', e.target.value)}
        />
        <Input
          label="Document origin type"
          value={form.document_origin_type}
          onChange={(e) => onFormFieldChange('document_origin_type', e.target.value)}
        />
        <Input
          label="Source entity type"
          value={form.source_entity_type}
          onChange={(e) => onFormFieldChange('source_entity_type', e.target.value)}
        />
        <Input
          label="Deliverable type"
          value={form.deliverable_type}
          onChange={(e) => onFormFieldChange('deliverable_type', e.target.value)}
        />
        <Input
          label="Template key"
          value={form.template_key}
          onChange={(e) => onFormFieldChange('template_key', e.target.value)}
        />
        <Input
          label="Export format"
          value={form.export_format}
          onChange={(e) => onFormFieldChange('export_format', e.target.value)}
        />
        <Input
          label="Package format"
          value={form.package_format}
          onChange={(e) => onFormFieldChange('package_format', e.target.value)}
        />
        <Input
          label="Selected document count"
          value={form.selected_document_count}
          onChange={(e) => onFormFieldChange('selected_document_count', e.target.value)}
        />
        <Select
          label="Partner access"
          value={form.partner_access}
          onValueChange={(v: string) => onFormFieldChange('partner_access', v)}
          options={[
            { value: 'false', label: 'false' },
            { value: 'true', label: 'true' },
          ]}
        />
        <Select
          label="Generated by AI"
          value={form.generated_by_ai}
          onValueChange={(v: string) => onFormFieldChange('generated_by_ai', v)}
          options={[
            { value: '', label: '(unset)' },
            { value: 'false', label: 'false' },
            { value: 'true', label: 'true' },
          ]}
        />
        <Select
          label="Has evidence links"
          value={form.has_evidence_links}
          onValueChange={(v: string) => onFormFieldChange('has_evidence_links', v)}
          options={[
            { value: '', label: '(unset)' },
            { value: 'false', label: 'false' },
            { value: 'true', label: 'true' },
          ]}
        />
        <Select
          label="Include archived documents"
          value={form.include_archived_documents}
          onValueChange={(v: string) => onFormFieldChange('include_archived_documents', v)}
          options={[
            { value: 'false', label: 'false' },
            { value: 'true', label: 'true' },
          ]}
        />
      </div>

      <div className="flex gap-2">
        <Button variant="primary" size="sm" loading={loading} onClick={() => void onEvaluate()}>
          Evaluate
        </Button>
        <Button variant="ghost" size="sm" onClick={onReset}>
          Reset
        </Button>
      </div>

      {error ? (
        <Typography variant="small" tone="error">
          {error}
        </Typography>
      ) : null}

      {result ? (
        <div className="space-y-2 rounded border border-border bg-muted/20 p-3 text-sm">
          <div>
            <strong>Decision:</strong>{' '}
            {result.allowed ? (result.effect === 'warn' ? 'ALLOW (warn)' : 'ALLOW') : 'DENIED'} · effect=
            {result.effect}
          </div>
          {result.blocked_reasons.length > 0 ? (
            <div>
              <strong>Blocked:</strong> {result.blocked_reasons.join('; ')}
            </div>
          ) : null}
          {result.warnings.length > 0 ? (
            <div>
              <strong>Warnings:</strong> {result.warnings.join('; ')}
            </div>
          ) : null}
          {result.suggested_actions.length > 0 ? (
            <div>
              <strong>Suggested:</strong> {result.suggested_actions.join('; ')}
            </div>
          ) : null}
          <div>
            <strong>Matched rules:</strong> {result.matched_rules.length}
          </div>
          {canViewRuleDetails && result.matched_rules.length > 0 ? (
            <ul className="list-disc pl-4">
              {result.matched_rules.map((rule) => (
                <li key={rule.rule_id}>
                  {rule.policy_key}/{rule.rule_key} ({rule.effect}) — {rule.explanation}
                </li>
              ))}
            </ul>
          ) : null}
        </div>
      ) : null}
    </div>
  )
}
