import type { BulkImportFormatGuide } from '@/shared/lib/bulkImportFormat'
import { SCREEN_MODE_CODE_OPTIONS, TRIGGER_ACTION_CODE_OPTIONS } from '../../domain/enums/screen-spec.enum'
import { SCREEN_IMPORT_FULL_MAX_ITEMS } from '../../domain/model/screen-spec-import'

const MODE_CODES = [...SCREEN_MODE_CODE_OPTIONS]
const TRIGGERS = [...TRIGGER_ACTION_CODE_OPTIONS]

export const SCREEN_FULL_SPEC_IMPORT_GUIDE: BulkImportFormatGuide = {
  entityLabel: 'Screen full spec',
  maxItems: SCREEN_IMPORT_FULL_MAX_ITEMS,
  notes: [
    'How to import: (1) Create components on Browse if fields will use componentCode. (2) Paste a project UUID in Default project ID, or put projectId on every item. (3) Paste JSON as { "items": [ ... ] } or a bare array. (4) Submit — the job returns 202; this page polls until each screen succeeds or fails.',
    'Max 200 screens per job. Duplicate code in the same file is rejected on the client.',
    'Each item is one screen: code + name, optional routePath, then nested modes, fields, processItems, eventItems. There is no sections array — only fields.',
    'Excel on this same tab only creates empty screens (code, name, routePath) via …/screens/bulk. Use this JSON for modes, fields, validations, processes, and events.',
    'componentCode must already exist on this application. processItems and eventItems require content. modeCode must be CREATE | VIEW | EDIT | SEARCH | DIALOG.',
    'ruleParamJson / conditionJson may be a JSON string or an object (the client stringifies objects).',
    'targetScreenCode on events is another screen code (can be in the same payload). triggerFieldKey / targetFieldKey are fieldKey values, not UUIDs.',
  ],
  fields: [
    { name: 'projectId', required: true, type: 'uuid', description: 'Project UUID. Omit only if Default project ID is filled on this page.' },
    { name: 'code', required: true, type: 'string', description: 'Screen code, unique in the application (max 50).' },
    { name: 'name', required: true, type: 'string', description: 'Screen display name (max 255).' },
    { name: 'routePath', required: false, type: 'string', description: 'Client route, e.g. /login.' },
    {
      name: 'modes[].modeCode',
      required: true,
      type: 'enum',
      enumValues: MODE_CODES,
      description: 'Screen mode.',
    },
    { name: 'modes[].name', required: true, type: 'string', description: 'Mode label shown in the UI (Create, View, …).' },
    { name: 'modes[].displayOrder', required: false, type: 'integer', description: 'Sort order; otherwise insertion order.' },
    { name: 'fields[].fieldKey', required: true, type: 'string', description: 'Stable key (e.g. email). Used by process/event targetFieldKey / triggerFieldKey.' },
    { name: 'fields[].label', required: true, type: 'string', description: 'Label on Defines (Field).' },
    { name: 'fields[].fieldType', required: true, type: 'string', description: 'Control type, e.g. INPUT, TEXT, DATE, BOOLEAN.' },
    { name: 'fields[].description', required: false, type: 'string', description: 'Optional help text.' },
    { name: 'fields[].required', required: false, type: 'boolean', description: 'Default required when a mode has no modeConfig.' },
    { name: 'fields[].maxLength', required: false, type: 'integer', description: 'Goes to Defines Length.' },
    { name: 'fields[].remark', required: false, type: 'string', description: 'Optional remark.' },
    { name: 'fields[].displayOrder', required: false, type: 'integer', description: 'Field order on the screen.' },
    { name: 'fields[].componentCode', required: false, type: 'string', description: 'Existing component code in this app (not a UUID).' },
    {
      name: 'fields[].modeConfigs[].modeCode',
      required: true,
      type: 'enum',
      enumValues: MODE_CODES,
      description: 'Which mode this config applies to.',
    },
    { name: 'fields[].modeConfigs[].isVisible', required: false, type: 'boolean', description: 'true → 〇 on Defines for that mode.' },
    { name: 'fields[].modeConfigs[].isRequired', required: false, type: 'boolean', description: 'Required in that mode.' },
    { name: 'fields[].modeConfigs[].isReadonly', required: false, type: 'boolean', description: 'Read-only in that mode.' },
    { name: 'fields[].modeConfigs[].defaultValue', required: false, type: 'string', description: 'Default value for Defines.' },
    { name: 'fields[].validations[].ruleTypeCode', required: true, type: 'string', description: 'Workspace rule type, e.g. EMAIL, MAX_LENGTH, REQUIRED, REGEX.' },
    {
      name: 'fields[].validations[].modeCode',
      required: false,
      type: 'enum',
      enumValues: MODE_CODES,
      description: 'Limit the rule to one mode; omit to apply on all modes.',
    },
    { name: 'fields[].validations[].ruleParamJson', required: false, type: 'string | object', description: 'Rule params, e.g. {"maxLength":255}.' },
    { name: 'fields[].validations[].errorMessage', required: false, type: 'string', description: 'Message shown on Validation sheet.' },
    { name: 'fields[].validations[].remark', required: false, type: 'string', description: 'Optional remark.' },
    { name: 'processItems[].content', required: true, type: 'string', description: 'What happens (Excel Get lines).' },
    { name: 'processItems[].title', required: false, type: 'string', description: 'Outline heading, e.g. 1. Init.' },
    {
      name: 'processItems[].modeCode',
      required: false,
      type: 'enum',
      enumValues: MODE_CODES,
      description: 'Limit to one mode.',
    },
    { name: 'processItems[].targetFieldKey', required: false, type: 'string', description: 'Related fieldKey.' },
    { name: 'processItems[].sourceTable', required: false, type: 'string', description: 'Excel Table / Database sheet.' },
    { name: 'processItems[].conditionNote', required: false, type: 'string', description: 'Excel Condition.' },
    { name: 'eventItems[].content', required: true, type: 'string', description: 'What the event does (Excel Get).' },
    { name: 'eventItems[].title', required: false, type: 'string', description: 'Outline heading, e.g. Submit.' },
    {
      name: 'eventItems[].triggerActionCode',
      required: false,
      type: 'enum',
      enumValues: TRIGGERS,
      description: 'How the event fires.',
    },
    { name: 'eventItems[].triggerFieldKey', required: false, type: 'string', description: 'Field that fires the event (fieldKey).' },
    {
      name: 'eventItems[].modeCode',
      required: false,
      type: 'enum',
      enumValues: MODE_CODES,
      description: 'Limit to one mode.',
    },
    { name: 'eventItems[].conditionNote', required: false, type: 'string', description: 'Excel Condition.' },
    { name: 'eventItems[].targetScreenCode', required: false, type: 'string', description: 'Navigate to this screen code.' },
    {
      name: 'eventItems[].targetModeCode',
      required: false,
      type: 'enum',
      enumValues: MODE_CODES,
      description: 'Target mode after navigate.',
    },
  ],
  sample: {
    items: [
      {
        projectId: '00000000-0000-0000-0000-000000000001',
        code: 'LOGIN',
        name: 'Login',
        routePath: '/login',
        modes: [
          { modeCode: 'CREATE', name: 'Create', displayOrder: 0 },
          { modeCode: 'VIEW', name: 'View', displayOrder: 1 },
        ],
        fields: [
          {
            fieldKey: 'email',
            label: 'Email',
            fieldType: 'INPUT',
            required: true,
            maxLength: 255,
            componentCode: 'TXT-EMAIL',
            modeConfigs: [
              { modeCode: 'CREATE', isVisible: true, isRequired: true, isReadonly: false },
              { modeCode: 'VIEW', isVisible: true, isRequired: false, isReadonly: true },
            ],
            validations: [{ ruleTypeCode: 'EMAIL', errorMessage: 'Invalid email' }],
          },
        ],
        processItems: [
          {
            title: '1. Init',
            content: 'Load login form',
            sourceTable: 'users',
            conditionNote: 'status = active',
          },
        ],
        eventItems: [
          {
            title: 'Submit',
            content: 'POST /api/login',
            triggerActionCode: 'CLICK',
            triggerFieldKey: 'email',
            targetScreenCode: 'HOME',
            targetModeCode: 'VIEW',
          },
        ],
      },
    ],
  },
}
