export { useProjectPhases } from './presentation/hooks/useProjectPhases'
export { usePhaseWatch } from './presentation/hooks/usePhaseWatch'
export { useCurrentNextPhase } from './presentation/hooks/useCurrentNextPhase'
export { PhaseWatchWidget } from './presentation/ui/PhaseWatchWidget'
export { CurrentNextPhaseWidget } from './presentation/ui/CurrentNextPhaseWidget'
export { PhaseFollowUpDrawer } from './presentation/ui/PhaseFollowUpDrawer'
export { CreatePhaseModal } from './presentation/ui/CreatePhaseModal'
export { PhaseBulkAddModal } from './presentation/ui/PhaseBulkAddModal'
export { PhaseJsonImportModal } from './presentation/ui/PhaseJsonImportModal'
export { PHASE_BULK_IMPORT_GUIDE } from './domain/model/phase-bulk-import.guide'
export { validatePhaseJsonImport } from './domain/model/phase-json-import.validation'
export type { ProjectPhase, CreateProjectPhasePayload } from './domain/model/phase'
export type { PhaseWatchProjectRow, PhaseWatchPhaseSummary } from './domain/model/phase-watch'
export { PhaseWatchFollowUpKind, PhaseWatchSignal } from './domain/enums/phase-watch.enum'
export * as phasesApi from './infrastructure/api/phases.api'
