export { NotificationInboxView } from './inbox/presentation/ui/NotificationInboxView'
export { NotificationSettingsView } from './settings/presentation/ui/NotificationSettingsView'
export { ProjectNotificationSettingsView } from './project-subscriptions'
export { useProjectNotifications } from './project-subscriptions'
export { useNotifications, useUnreadNotificationCount } from './inbox/presentation/hooks/useNotifications'
export { useNotificationSettings } from './settings/presentation/hooks/useNotificationSettings'
export { resolveNotificationAction } from './lib/NotificationActionResolver'
export * as userNotificationsApi from './inbox/infrastructure/api/notifications.api'
export * as notificationPreferencesApi from './settings/infrastructure/api/preferences.api'
export * as projectNotificationsApi from './project-subscriptions/api/project-notifications.api'
export type { UserNotification } from './inbox/domain/model/notification'
