export { WorkInboxView } from './presentation/ui/WorkInboxView'
export { SavedItemsView } from './presentation/ui/SavedItemsView'
export { GlobalSearchView } from './presentation/ui/GlobalSearchView'
export { useGlobalSearch } from './presentation/hooks/useGlobalSearch'
export { useWorkInbox } from './presentation/hooks/useWorkInbox'
export { useSavedItems } from './presentation/hooks/useSavedItems'
export * as productivityApi from './infrastructure/api/productivity.api'
export type { SearchResultItem, SearchResponse } from './domain/model/search'
export type { WorkInboxItem } from './domain/model/work-inbox'
export type { FavoriteItem, RecentItem, SavedView } from './domain/model/saved-items'
